# Generated by Django 2.2.13 on 2020-08-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowBoxDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('day', models.IntegerField(verbose_name='День')),
                ('hours', models.IntegerField(verbose_name='Часы')),
                ('minutes', models.IntegerField(verbose_name='Минуты')),
                ('seconds', models.IntegerField(verbose_name='Секунды')),
            ],
        ),
        migrations.CreateModel(
            name='GrowBoxSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimal_soil_humidity', models.IntegerField(verbose_name='Минимальная влажность грунта в процентах')),
                ('lamp_on_time', models.IntegerField(verbose_name='Время включения лампы в часах')),
                ('lamp_off_time', models.IntegerField(verbose_name='Время выключения лампы в часах')),
                ('pump_run_time', models.IntegerField(verbose_name='Время работы помпы в секундах')),
                ('data_sending_frequency', models.IntegerField(verbose_name='Таймер отправки данных с платы в секундах')),
                ('planting_date', models.CharField(default='2020-01-01', max_length=20, verbose_name='Дата посадки в формате: 2020-08-20')),
                ('days_before_harvest', models.IntegerField(default=0, verbose_name='Дней до предполагаемой технической спелости')),
            ],
        ),
        migrations.CreateModel(
            name='GrowBoxHistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temperature', models.IntegerField(verbose_name='Температура воздуха')),
                ('air_humidity', models.IntegerField(verbose_name='Влажность воздуха')),
                ('soil_humidity', models.IntegerField(verbose_name='Влажность грунта')),
                ('datetime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hvoya_app.GrowBoxDateTime')),
            ],
        ),
    ]
